version: "3"

tasks:
  create-db-schema:
    cmds:
      - atlas schema inspect -u sqlite://test.db -w

  create-swagger-doc:
    cmds:
      - ~/go/bin/swag init --parseDependency --parseInternal

  build:
    cmds:
      - go build -v main.go

  release-version:
    cmds:
      - rm -rf /pfad/zum/ordner 2>/dev/null || true
      - goreleaser release

  release-snapshot:
    cmds:
      - rm -rf /pfad/zum/ordner 2>/dev/null || true
      - goreleaser release --snapshot --clean
  run:
    cmds:
      - air main.go
